#!/bin/bash
# Validate that service urls return expected content
HEALTH_DIR=`dirname $0`
SCRIPTS_DIR=`dirname $HEALTH_DIR`
. $SCRIPTS_DIR/scriptrc
set -e

# Grab any OPENSTACK_URL* environment variables and validate content response
openstack_urls=`env| awk -F '=' '(/OPENSTACK_URL/){print $2 }'`
for url_check in $openstack_urls
do
    url=`echo $url_check| awk -F '|' '{print $1}'`
    expected_content=`echo $url_check| awk -F '|' '{print $2}'`
    wget -q -O - $url | grep -q "${expected_content//+/ }"
done

