#!/bin/bash

CHARM="openstack-dashboard"

PACKAGES="openstack-dashboard python-keystoneclient python-memcache memcached"
LOCAL_SETTINGS="/etc/openstack-dashboard/local_settings.py"

if [[ -e "$CHARM_DIR/lib/openstack-common" ]] ; then
  . $CHARM_DIR/lib/openstack-common
else
  juju-log "ERROR: Couldn't load $CHARM_DIR/lib/openstack-common." && exit 1
fi

set_or_update() {
  # set a key = value option in $LOCAL_SETTINGS
  local key=$1 value=$2
  [[ -z "$key" ]] || [[ -z "$value" ]] &&
    juju-log "$CHARM set_or_update: ERROR - missing parameters" && return 1
  grep -q "^$key = \"$value\"" "$LOCAL_SETTINGS" &&
    juju-log "$CHARM set_or_update: $key = $value already set" && return 0
  if grep -q "^$key = " "$LOCAL_SETTINGS" ; then
    juju-log "$CHARM set_or_update: Setting $key = $value"
    cp "$LOCAL_SETTINGS" /etc/openstack-dashboard/local_settings.last
    sed -i "s|\(^$key = \).*|\1\"$value\"|g" "$LOCAL_SETTINGS" || return 1
  else
    juju-log "$CHARM set_or_update: Adding $key = $value"
    echo "$key = \"$value\"" >>$LOCAL_SETTINGS || return 1
  fi
  return 0
}
