#!/bin/bash
set -e 

FORMULA_DIR=$(dirname $0)
ARG0=${0##*/}

if [[ -e $FORMULA_DIR/horizon-common ]] ; then
  . $FORMULA_DIR/horizon-common
else
  echo "ERROR: Could not load horizon-common from $FORMULA_DIR"
fi

function install_hook {
  add_ppa
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get -y install $PACKAGES
  set_or_update CACHE_BACKEND "memcached://127.0.0.1:11211/"
  open-port 80
}

function db_joined {
  # TODO
  # relation-set database, username, hostname 
  return 0
}

function db_changed {
  # TODO
  # relation-get password, private-address
  return 0
}

function keystone_joined {
  # service=None lets keystone know we don't need anything entered
  # into the service catalog.  we only really care about getting the
  # private-address from the relation
  relation-set service="None" region="None" public_url="None" \
               admin_url="None" internal_url="None"
}

function keystone_changed {
  service_url="http://$(relation-get private-address):5000/v2.0"
  set_or_update OPENSTACK_KEYSTONE_URL "$service_url"
  service apache2 restart
}

case $ARG0 in
  "install") install_hook ;;
  "start") exit 0 ;;
  "stop") exit 0 ;;
  "shared-db-relation-joined") db_joined ;;
  "shared-db-relation-changed") db_changed;;
  "identity-service-relation-joined") keystone_joined;;
  "identity-service-relation-changed") keystone_changed;;
esac
