#!/bin/bash
set -e 

FORMULA_DIR=$(dirname $0)
ARG0=${0##*/}

if [[ -e $FORMULA_DIR/horizon-common ]] ; then
  . $FORMULA_DIR/horizon-common
else
  echo "ERROR: Could not load horizon-common from $FORMULA_DIR"
fi

function install_hook {
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get -y install $PACKAGES
  open-port 80
}

function db_joined {
  # TODO
  # relation-set database, username, hostname 
  return 0
}

function db_changed {
  # TODO
  # relation-get password, private-address
  return 0
}

function keystone_joined {
  # we simply request the default role from keystone
  local role=$(config-get default-role)
  relation-set role="$role"
}

function keystone_changed {
  # keystone returns with ports for admin and auth URLs + an admintoken
  local token=$(relation-get admin_token)
  local service_port=$(relation-get service_port)
  local auth_port=$(relation-get auth_port)
  [[ -z "$token" ]] || [[ -z "$service_port" ]] || [[ -z "$auth_port" ]] &&
    juju-log "keystone_changed: Missing relation data. Peer not ready?" && exit 0
  service_url="http://$(relation-get private-address):$service_port/v2.0"
  admin_url="http://$(relation-get private-address):$auth_port/v2.0"
  set_or_update OPENSTACK_KEYSTONE_URL "$service_url"
  set_or_update OPENSTACK_KEYSTONE_ADMIN_URL "$admin_url"
  set_or_update OPENSTACK_KEYSTONE_DEFAULT_ROLE "$(config-get default-role)"
  service apache2 restart
}

case $ARG0 in
  "install") install_hook ;;
  "start") exit 0 ;;
  "stop") exit 0 ;;
  "shared-db-relation-joined") db_joined ;;
  "shared-db-relation-changed") db_changed;;
  "keystone-service-relation-joined") keystone_joined;;
  "keystone-service-relation-changed") keystone_changed;;
esac
